trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/product-catalog/** 

pool: 
  name : ubuntu
  
stages:
  - stage: Test
    displayName: "Run Go Unit Tests"
    jobs:
      - job: GoTest
        steps:
          - checkout: self

          - task: GoTool@0
            inputs:
              version: '1.22.2'

          - script: |
              cd src/product-catalog
              go mod tidy
              go test ./... -v
            displayName: "Execute Go tests"

  - stage: buildandpush
    displayName: "Build and Push Docker Image"
    dependsOn: Test
    jobs:
      - job: BuildAndPush
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: 'docker'  # service connection name
              repository: 'adityakrs/product-catalog'
              command: 'buildAndPush'
              Dockerfile: 'src/product-catalog/Dockerfile'
              buildContext: 'src/product-catalog'

