trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - src/payment/** 

pool: 
  name: ubuntu
  
stages:
  - stage: Test
    displayName: "Run Go Unit Tests"
    jobs:
      - job: GoTest
        steps:
          - checkout: self

          - script: |
              cd src/payment
              go mod tidy
              go test ./... -v
            displayName: "Execute Go tests"
