trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/product-catalog/**

pool:
  name: ubuntu

stages:
  - stage: Test
    displayName: "Run Go Unit Tests"
    jobs:
      - job: GoTest
        steps:
          - checkout: self

          - task: GoTool@0
            inputs:
              version: '1.22.2'

          - script: |
              cd src/product-catalog
              go mod tidy
              go test ./... -v
            displayName: "Execute Go tests"

  - stage: sonar
    displayName: "SonarQube Analysis"
    dependsOn: Test
    jobs:
      - job: sonar
        steps:
          - checkout: self
          - task: SonarQubePrepare@7
            inputs:
              SonarQube: 'sonar'
              scannerMode: 'cli'
              cliScannerVersion: '4.8.0.2856'
              configMode: 'manual'
              cliProjectKey: 'product-catalog'
              cliProjectName: 'Product Catalog'
              cliSources: 'src/product-catalog'
          - task: SonarQubeAnalyze@7
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
          - task: SonarQubePublish@7
            inputs:
              pollingTimeoutSec: '300'

  - stage: buildandpush
    displayName: "Build and Push Docker Image"
    dependsOn: sonar
    jobs:
      - job: BuildAndPush
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: 'docker'  # service connection name
              repository: 'adityakrs/product-catalog'
              command: 'buildAndPush'
              Dockerfile: 'src/product-catalog/Dockerfile'
              buildContext: 'src/product-catalog'
